version: 2.1

orbs:
  node: circleci/node@3.0.0

jobs:
  build:
    docker:
      - image: node:16.13.1
    steps:
      - checkout
      - run:
          name: Install
          command: npm i
      - save_cache:
          paths:
            - node_modules
          key: dependencies-
      - run:
          name: CI
          command: npm ci
      - run:
          name: Gatsby build
          command: npm run build
      - run:
          name: set git config
          command: |
            npm install -g --silent gh-pages
            git config user.email $GITHUB_EMAIL
            git config user.name $GITHUB_NAME
      - add_ssh_keys:
          fingerprints:
            - '49:b9:0a:d8:f2:e4:37:22:b6:c8:82:38:89:4c:9d:0f'
      - run:
          name: deploy
          command: gh-pages -d public

workflows:
  build-deploy-workflow:
    jobs:
      - build
          filters:
            branches:
              only:
                - master
