name: Deploy # Github Action 이름

on:
  push:
    branches:
      - master # 빌드할 브랜치

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      GATSBY_CONTENTFUL_ACCESS_TOKEN: ${{ secrets.GATSBY_CONTENTFUL_ACCESS_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - uses: enriikke/gatsby-gh-pages-action@v2.2.0
        with:
          access-token: ${{ secrets.DEPLOY }}
          deploy-branch: gh-pages
